---
title: "06.3 - MethylKit: Tiles
---

# Load libraries & data
```{r}

library(dplyr)
library(ggplot2)
library(methylKit)
library(pheatmap)
library(rcolorbrewer)
library(tidyverse)

# Load object
load("output/methylkit/objects/methylkit_filtered.RData")

```

# Create tiles & PCA
```{r}

tiles <- tileMethylCounts(
  myobj_filtered,
  win.size = 1000,
  step.size = 1000
)

# Filter
tiles_filtered <- filterByCoverage(
  tiles,
  lo.count = 5,
  hi.perc = 99
)

# Unite
meth_tiles <- unite(tiles_filtered)

# PCA
PCASamples(meth_tiles)

# Differential methylation
diff_tiles <- calculateDiffMeth(meth_tiles)

# Extract
tiles_sig <- getMethylDiff(diff_tiles, difference=25, qvalue=0.01)

# Save
write.csv(tiles_sig,
  "output/methylkit/tiles/tiles_1kb_25pct_q001.csv")

# BED
bed <- data.frame(
  chr = tiles_sig$chr,
  start = tiles_sig$start,
  end = tiles_sig$end
)

write.table(bed,
  "output/methylkit/tiles/tiles_1kb_25pct_q001.bed",
  sep="\t", quote=FALSE, row.names=FALSE, col.names=FALSE)

```

